title: Just the Docs Exercise
description: Step by step with just the docs
theme: just-the-docs

url: https://ola-szewczyk.github.io/just_the_docs_exercise

aux_links:
  Template Repository: https://github.com/ola-szewczyk/just-the-docs-template

color_scheme: dark
